[tasks.lint]
extends = "ext:lint"

[tasks.test]
extends = "ext:test"

[tasks.test-external]
extends = "ext:test-external"

[tasks.typecheck]
extends = "ext:typecheck"

[tasks.typecheck-strict]
extends = "ext:typecheck-strict"

[tasks.type-aware]
extends = "ext:type-aware"

[tasks.ci]
extends = "ext:ci"

[tasks.check]
extends = "ext:check"
